spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/math_verse_db?currentSchema=public
    username: math_user
    password: admin
  flyway:
    schemas: public
  jpa:
    hibernate:
      ddl-auto: validate

ai:
  gateway:
    url: http://localhost:8083
jwt:
    secret: ${JWT_SECRET:qwertyuiopasdfghjklkzxcvbnm1478523690123456789}  # ≥ 32 байта
    expiration-ms: 3600000